# Generated by Django 3.2.6 on 2021-08-20 16:58

from django.db import migrations

def add_expansion(apps, schema_editor):
    expansions = {
        "ZKR":["Zendikar Rising", "25/09/2020"],
        "ELD":["Throne of Eldraine", "4/10/2019"],
        "IKO":["Ikoria: Lair of the Behemoths", "17/04/2020"],
        "TBD":["Theros Beyond Death", "24/01/2020"],
        "M20":["Magic 2020", "12/07/2019"],
    }
    Expansion = apps.get_model('MTG_Tracker', 'Expansion')
    for expansion_code in expansions:
        e = Expansion(code=expansion_code, name=expansions[expansion_code][0], release_date=expansions[expansion_code][1])
        e.save()

class Migration(migrations.Migration):

    dependencies = [
        ('MTG_Tracker', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_expansion),
    ]
