# Generated by Django 3.2.6 on 2021-08-20 16:58

from django.db import migrations

def add_expansion(apps, schema_editor):
    expansions = {
        "ZKR":["Zendikar Rising", "2020-09-25"],
        "ELD":["Throne of Eldraine", "2019-10-04"],
        "IKO":["Ikoria: Lair of the Behemoths", "2020-04-17"],
        "TBD":["Theros Beyond Death", "2020-01-24"],
        "M20":["Magic 2020", "2019-07-12"],
    }
    Expansion = apps.get_model('MTG_Tracker', 'Expansion')
    for expansion_code in expansions:
        e = Expansion(code=expansion_code, name=expansions[expansion_code][0], release_date=expansions[expansion_code][1])
        e.save()

class Migration(migrations.Migration):

    dependencies = [
        ('MTG_Tracker', '0002_expansion_release_date'),
    ]

    operations = [
        migrations.RunPython(add_expansion),
    ]
