# Generated by Django 3.2.6 on 2021-08-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MTG_Tracker', '0002_auto_20210820_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='expansion',
            name='release_date',
            field=models.DateField(null=True),
        ),
    ]
